(library
 (name mcp_server_integration_test)
 (modules mcp_server_integration_test)
 (libraries
  core
  expect_test_helpers_core
  eio
  eio_main
  eio.mock
  eio.unix
  ochat.mcp_server_core
  ochat.mcp_server_http
  ochat.mcp_client
  ochat.mcp_types
  piaf)
 (inline_tests)
 (preprocess
  (pps ppx_jane ppx_expect)))

(library
 (name mcp_transport_http_sse_test)
 (modules mcp_transport_http_sse_test)
 (libraries
  core
  expect_test_helpers_core
  eio
  eio_main
  eio.mock
  eio.unix
  piaf
  uri
  ochat.mcp_transport)
 (inline_tests)
 (preprocess
  (pps ppx_jane ppx_expect)))

(library
 (name mcp_transport_http_test)
 (modules mcp_transport_http_test)
 (libraries
  core
  expect_test_helpers_core
  eio
  eio_main
  eio.mock
  eio.unix
  piaf
  uri
  ochat.mcp_transport)
 (inline_tests)
 (preprocess
  (pps ppx_jane ppx_expect)))

(library
 (name mcp_client_http_test)
 (modules mcp_client_http_test)
 (libraries
  core
  expect_test_helpers_core
  eio
  eio_main
  eio.mock
  eio.unix
  piaf
  uri
  ochat.mcp_client
  ochat.mcp_types)
 (inline_tests)
 (preprocess
  (pps ppx_jane ppx_expect)))
