(** Spawn and drive a *forked* assistant session.

    The module implements the runtime side of the built-in {!file:definitions.ml#module-Fork} GPT
    function called ["fork"].  Calling {!execute} clones the current
    conversation, runs a nested completion loop that can itself invoke
    arbitrary tools – including recursive forks – and finally returns the
    forked assistant’s textual reply.

    The implementation is split between:

    • {!execute}, a **blocking** wrapper used by the ordinary
      non-streaming {!Response_loop}; and
    • an internal [run_stream] helper (not exposed in the [.mli]) that
      performs the actual streaming request and forwards every event back
      to the parent so UIs may surface fork progress in real-time. *)

(* -------------------------------------------------------------------- *)
(*  Public API                                                           *)
(* -------------------------------------------------------------------- *)

module Invocation_id : sig
  type t

  val create : unit -> t
  val to_string : t -> string
end

(** [allocator ~parent_namespace invocation_id] creates an isolated child
    allocator. The invocation identity is distinct from provider IDs and tool
    [call_id]. *)
val allocator : parent_namespace:string -> Invocation_id.t -> History_entry.Allocator.t

(** [execute env history call_id arguments tools tool_tbl on_event on_fn_out ()]
    runs a forked agent to completion and returns its final reply.

    Arguments:
    • [env] – the standard Eio environment obtained from [Eio_main.run].
      Only [env#net] and [env#cwd] are used internally.
    • [history] – full message history **before** the call to the
      [fork] tool.  The list is reused verbatim; no deep-copy is needed.
    • [call_id] – identifier of the tool invocation, echoed back in all
      generated [function_call_output] items so the parent can match
      streamed data to the correct call.
    • [arguments] – JSON payload passed to the tool, as received from the
      OpenAI API.  It is decoded with
      [Definitions.Fork.input_of_string] to extract the command and
      positional parameters given to the fork.
    • [tools] – flat list of available tools, forwarded unchanged to the
      nested completion request so the forked agent has access to the
      exact same capabilities as its parent.
    • [tool_tbl] – runtime dispatch table mapping tool names to
      implementations.  The table **must** contain an entry called
      ["fork"] that points back to {!execute}, otherwise recursive forks
      will fail with a key-error.
    • [on_event] – callback invoked for **every** low-level streaming
      event produced by the nested request, including tool-call
      arguments, deltas and reasoning sections.
    • [on_fn_out] – callback invoked whenever the fork produces a new
      [function_call_output] block.  This is necessary because assistants
      frequently stream partial answers before the final message ends.

    Optional parameters:
    • [?temperature] – sampling temperature forwarded to the nested
      request; defaults to the OpenAI model default.
    • [?max_output_tokens] – explicit upper bound on generated tokens.
    • [?reasoning] – whether reasoning items should be generated (see
      {!Openai.Responses.Request.Reasoning}).

    Returns: the concatenation of all assistant messages generated by the
    fork *after* the initial history, separated by newlines.

    The call is synchronous: the function only returns once the forked
    agent has either terminated normally or the OpenAI request hit its
    server-side token limit.

    Child execution is identity-bearing; parent entries retain their IDs and
    child-created entries use the invocation allocator. *)

(** [execute_entries] runs a child over a projection of [history]. Parent
    entries remain unchanged and child activity is scoped by [invocation_id].
    The child history is isolated; only the returned text becomes parent
    canonical state. *)
val execute_entries
  :  env:Eio_unix.Stdenv.base
  -> allocator:History_entry.Allocator.t
  -> history:History_entry.t list
  -> invocation_id:Invocation_id.t
  -> call_id:string
  -> arguments:string
  -> tools:Openai.Responses.Request.Tool.t list
  -> tool_tbl:(string, Ochat_function.runner) Base.Hashtbl.t
  -> on_event:(Openai.Responses.Response_stream.t -> unit)
  -> ?on_sourced_event:(Sourced_response_event.t -> unit)
  -> ?on_tool_execution:(Tool_execution_event.t -> unit)
  -> on_fn_out:(Openai.Responses.Function_call_output.t -> unit)
  -> ?temperature:float
  -> ?max_output_tokens:int
  -> ?reasoning:Openai.Responses.Request.Reasoning.t
  -> unit
  -> string

(** [history_entries ~allocator ~history ~arguments ~call_id] preserves the
    parent entries and appends one child-owned synthetic instruction entry. *)
val history_entries
  :  allocator:History_entry.Allocator.t
  -> history:History_entry.t list
  -> arguments:string
  -> call_id:string
  -> History_entry.t list
