open! Core

type moderator =
  { manager : Moderator_manager.t
  ; session_id : string
  ; session_meta : Jsonaf.t
  ; runtime_policy : Runtime_semantics.policy
  }

type moderated_tool_call =
  { call_item : Openai.Responses.Item.t
  ; kind : Tool_call.Kind.t
  ; name : string
  ; payload : string
  ; synthetic_result : Openai.Responses.Tool_output.Output.t option
  ; runtime_requests : Moderation.Runtime_request.t list
  }

(** [prepare_turn_inputs ?moderator ~available_tools ~now_ms ~history] applies
    the moderator [turn_start] hook and returns the effective request history
    for the next model call. Without a moderator, it returns [history]
    unchanged. *)
val prepare_turn_inputs
  :  moderator:moderator option
  -> available_tools:Openai.Responses.Request.Tool.t list
  -> now_ms:int
  -> history:Openai.Responses.Item.t list
  -> (Openai.Responses.Item.t list, string) result

(** [finish_turn ?moderator ~available_tools ~now_ms ~history] applies the
    moderator [turn_end] hook after a streamed turn completes and returns
    surfaced runtime requests emitted during [turn_end] (including requests
    produced by drained internal events). Without a moderator, it is a no-op
    returning [[]]. *)
val finish_turn
  :  moderator:moderator option
  -> available_tools:Openai.Responses.Request.Tool.t list
  -> now_ms:int
  -> history:Openai.Responses.Item.t list
  -> (Moderation.Runtime_request.t list, string) result

(** [moderate_tool_call ...] applies the [pre_tool_call] moderation hook and
    returns the effective tool invocation together with any surfaced runtime
    requests. Rejected calls return a synthetic output payload instead of an
    executable invocation. *)
val moderate_tool_call
  :  moderator:moderator option
  -> available_tools:Openai.Responses.Request.Tool.t list
  -> now_ms:int
  -> history:Openai.Responses.Item.t list
  -> kind:Tool_call.Kind.t
  -> name:string
  -> payload:string
  -> call_id:string
  -> item_id:string option
  -> (moderated_tool_call, string) result

(** [handle_tool_result ...] applies the [post_tool_response] moderation hook
    for [item], then emits [message_appended] for the canonical history item,
    drains queued internal events, and returns surfaced runtime requests. *)
val handle_tool_result
  :  moderator:moderator option
  -> available_tools:Openai.Responses.Request.Tool.t list
  -> now_ms:int
  -> history:Openai.Responses.Item.t list
  -> name:string
  -> kind:Tool_call.Kind.t
  -> item:Openai.Responses.Item.t
  -> (Moderation.Runtime_request.t list, string) result

(** [run_completion_stream_in_memory_v1 ~env ~history ~tools ()] streams a
    ChatMarkdown conversation **held entirely in memory**.

    Compared to {!run_completion_stream} this helper:

    • Accepts an explicit [history] (list of {!Openai.Responses.Item.t})
      instead of reading a `.chatmd` file from disk.
    • Returns the *complete* history after all assistant turns and tool
      calls have been resolved.
    • Never touches the filesystem except for the persistent cache under
      `[~/.chatmd]`, making it suitable for unit-tests or server back-ends
      where direct file IO is undesirable.

    Optional callbacks mirror the streaming variant:

    • [?on_event] – invoked for each streaming event received from the
      OpenAI API (token deltas, item completions, …). Defaults to a no-op.
    • [?on_fn_out] – executed after each tool call completes, allowing the
      caller to react to side-effects without waiting for the final
      assistant answer.

    @param env      Standard Eio runtime environment.
    @param history  Initial conversation state.
    @param tools    Compile-time list of tool definitions visible to the
                    model.  Pass [[]] for none.
    @param tool_tbl Optional lookup table generated from [tools].  The
                    default builds a fresh table via
                    {!Ochat_function.functions} when omitted.
    @param temperature Temperature override forwarded the OpenAI request.
    @param max_output_tokens Hard cap on the number of tokens generated by
           the model per request.
    @param reasoning Optional reasoning settings forwarded to the API.
    @param moderator Optional session-scoped moderator runtime. When present,
           the driver applies [turn_start] before each model request,
           [message_appended] as canonical history items are produced,
           [pre_tool_call] and [post_tool_response] around tool execution,
           and [turn_end] after each streamed turn, using the moderator
           overlay to compute the effective request history.
    @param on_runtime_request Optional callback invoked for surfaced moderator
           runtime requests such as compaction or end-session notifications.

    @param history_compaction If [true], the function will compact the
           history so that multiple calls to the same file are replaced with a
           single call that points to the latest file content. Outputs for older calls are replaced with a
           place holder that points to the latest call output (stale) file content removed — see newer read_file output later

    @return The updated [history], i.e. the concatenation of the original
            [history] and every item produced during the streaming loop.

    @raise Any exception bubbled-up by the OpenAI client or user-supplied
           tool functions.  The function does **not** swallow errors. *)
val run_completion_stream_in_memory_v1
  :  env:Eio_unix.Stdenv.base
  -> ?datadir:Eio.Fs.dir_ty Eio.Path.t
  -> history:Openai.Responses.Item.t list
  -> ?on_event:(Openai.Responses.Response_stream.t -> unit)
  -> ?on_fn_out:(Openai.Responses.Function_call_output.t -> unit)
  -> ?on_tool_out:(Openai.Responses.Item.t -> unit)
  -> tools:Openai.Responses.Request.Tool.t list option
  -> ?tool_tbl:(string, string -> Openai.Responses.Tool_output.Output.t) Hashtbl.t
  -> ?temperature:float
  -> ?max_output_tokens:int
  -> ?reasoning:Openai.Responses.Request.Reasoning.t
  -> ?moderator:moderator
  -> ?on_runtime_request:(Moderation.Runtime_request.t -> unit)
  -> ?history_compaction:bool
  -> ?parallel_tool_calls:bool
  -> ?meta_refine:bool
  -> ?system_event:string Eio.Stream.t
  -> ?model:Openai.Responses.Request.model
  -> ?prompt_cache_key:string
  -> ?prompt_cache_retention:string
  -> unit
  -> Openai.Responses.Item.t list
