(version 1)
(server
 ((data_dir ./data)
  (unix_socket ./agent.sock)
  (http ((enabled false)))
  (session_helpers
   (((tool_name session_bridge)
     (executable ./public/helper)
     (executable_sha256 REPLACE_WITH_HELPER_SHA256)
     (operations (create send read status wait stop reference validate))
     (read_roots (./public))
     (environment ("PATH=/bin:/usr/bin" "PAGER=cat" "GIT_PAGER=cat" "TERM=dumb" "NO_COLOR=1"))
     (private_paths ()))
    ((tool_name session_view)
     (executable ./public/helper)
     (executable_sha256 REPLACE_WITH_HELPER_SHA256)
     (operations (read status wait))
     (read_roots (./public))
     (environment ("PATH=/bin:/usr/bin" "PAGER=cat" "GIT_PAGER=cat" "TERM=dumb" "NO_COLOR=1"))
     (private_paths ()))))))
(workspaces
 (((id examples)
   (source (physical ./public))
   (access shared_write)
   (prompt_limits (((prompt coordinator) (max_root_agents 2) (overflow queue)))))))
(prompts
 (((id coordinator)
   (path ./agent.chatmd)
   (description "Helper-backed persisted specialists and response watchers")
   (allowed_workspaces (examples))
   (permission_profile interactive)
   (enabled true))))
(permission_profiles
 (((id interactive)
   (tool_default ask)
   (approval_timeout none)
   (approval_fallback deny)
   (manifest_authorization require_grant))))
(manifest_grants ())
