(library
 (name chatmd)
 (public_name ochat.chatmd)
 (wrapped false)
 (modules
  chatmd_ast
  chatmd_lexer
  chatmd_parser
  chatmd_attributes
  chatmd_import_expansion
  chatmd_script_declaration
  chatmd_moderator_runtime_declaration
  chatmd_read_file_spec
  chatmd_read_file_declaration
  chatmd_shell_declaration
  chatmd_shell_serialization
  prompt)
 (libraries
  core
  str
  menhirLib
  jsonaf
  io
  ochat.meta_prompting
  ochat.history_entry
  ochat.chatmd_shell_spec)
 (preprocess
  (pps ppx_jane ppx_jsonaf_conv)))

(menhir
 (modules chatmd_parser)
 (flags --table))

(ocamllex chatmd_lexer)
