(library
 (name provider_runtime)
 (public_name ochat.provider_runtime)
 (libraries ochat.operator_authorization core eio ochat.provider_secret_store ochat.provider_operator ochat.inference_host ochat.inference_runtime ochat.inference ochat.openai ochat.agent_protocol ochat.agent_server)
 (preprocess (pps ppx_jane)))
